### ISSUE TITLE
issue by export pdf

### ISSUE THREAD

**Issue by lincongfei** [long21wt/Demolition-Planing-Tool#1]
click "export" button:
there is a bug on line 327.
pdf can't not be exported

**Comment by long21wt** [comment]
> click "export" button:
there is a bug on line 327.
pdf can't not be exported

How can I reproduce the issue ?

**Comment by lincongfei** [comment]
> 
sorry forgot to write it.

- create a new project
- add several quantities using "Add Quantities" button
- click "Export PDF"

is this enough or you need more info about it?:)

**Comment by long21wt** [comment]
It has to be specific, for example you can record a video or tell me the exact quantities/wasteID/floor/room you added by a screenshot.
Which exception does the code raise ? Do you use the latest commit ?

Sorry for asking too detailed :) but without I can't reproduce the issue

**Comment by long21wt** [comment]
Ok I know where the issue from

**Comment by lincongfei** [comment]
> It has to be specific, for example you can record a video or tell me the exact quantities/wasteID/floor/room you added by a screenshot. Which exception does the code raise ? Do you use the latest commit ?
> 
> Sorry for asking too detailed :) but without I can't reproduce the issue

it' totally ok because i'm now working with plug-in test and the issuse report is exact what you said. i'll add more details if i add new report in the next days :) 

and for this issue i think it's a generally issue so i didn't add to much infos...
