### ISSUE TITLE
can not delete item in listbox "overview current quantities"

### ISSUE THREAD

**Issue by lincongfei** [long21wt/Demolition-Planing-Tool#2]
process:
- create a new project
- add several quantities using "Add Quantities" button
- select one of the item in listbox "overview current quantities"
- click "Delete Item"
- show pop-up window "please select a item to delete it"

Soll-Stand:
if select an item in listbox "overview current quantities" and click "delete item", this item can be deleted.

**Comment by long21wt** [comment]
Thanks let me check
