### ISSUE TITLE
Order PDF Document

### ISSUE THREAD

**Issue by kaetezierhut** [long21wt/Demolition-Planing-Tool#3]
When I am exporting the PDF there is no order in the Document. It still orderen like the listBox in der Form

**Comment by long21wt** [comment]
Can you give me examples to reproduce the issues ? e.g., steps to choose floor, room, wasteid, quantities
Could be more specific like your expectation output and current output ? Screenshot would be nice

**Comment by kaetezierhut** [comment]
![grafik](https://user-images.githubusercontent.com/117446770/207365552-a72b4673-969b-4cbe-a30b-e49cba4cc6af.png)

Thats just a small drawing, maybe you understand it better this way.. From a layout point of view I would prefer the second version but I guess the first one is easier and also okay :)

**Comment by long21wt** [comment]
Ok so the first column will be the wasteID, and you want to sort by the wasteID first?
